### ISSUE TITLE
Adding predefined topologies to topogen

### ISSUE THREAD

**Issue by Asaadkaadan** [OUWECAD/MOWE#3]
- Spherical terminal (full transceiver, hexagons RX only, hexagons TX only, full receiver, full transceiver)

**Comment by nishaal-parmar** [comment]
Generated some sample flat networks (7, 18, 35, 127), for later testing use (fully connected, only using hexagon rx modules); will also make some spheres of varying sizes once these are added.  Also added a command list for each so if you need to use them as a base or modify them you can copy/paste into Matlab and save some time.

**Comment by Asaadkaadan** [comment]
Thanks. The spheres have only one size based on module dimensions. There are different configurations for them other than size thus you don't need to worry about them. Let's test some of your algorithms for the flat ones for now
